30980 MainProcess 2023-05-03 11:08:42,360
Traceback (most recent call last):
  File "C:\Users\getsg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 689, in main
    main_entry(sys.argv[1:])
  File "C:\Users\getsg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 677, in main_entry
    args.func(ctx, args)
  File "C:\Users\getsg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 214, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\getsg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\generate.py", line 152, in process
    self._obfuscate_scripts()
  File "C:\Users\getsg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\generate.py", line 117, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\getsg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 65, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 783, in generate_obfuscated_script
  File "C:\Users\getsg\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 539, in process
  File "<maker>", line 545, in coserialize
  File "<maker>", line 615, in _build_ast_body
RuntimeError: out of license
